apiVersion: apps/v1
kind: Deployment
metadata:
  name: planna-server
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 941283148711.dkr.ecr.us-west-2.amazonaws.com/plannaservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000